workflows:
  expo-build:
    name: Expo Android Build
    max_build_duration: 60

    environment:
      node: 18

    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Install Expo
        script: |
          npm install -g expo

      - name: Generate Android folder
        script: |
          npx expo prebuild --platform android --no-install

      - name: Install node modules again
        script: |
          npm install

      - name: Build APK
        script: |
          cd android
          ./gradlew assembleRelease

    artifacts:
      - android/app/build/outputs/**/*.apk
