workflows:
  expo-build:
    name: Expo Android Build
    max_build_duration: 60

    environment:
      node: 18

    scripts:
  - name: Install dependencies
    script: |
      npm install
      npx expo install

  - name: Expo prebuild
    script: |
      npx expo prebuild --platform android

  - name: Build APK
    script: |
      cd android
      ./gradlew assembleRelease
